### ISSUE TITLE
Jest issue TypeError: generateConfig[fn] is not a function

### ISSUE THREAD

**Issue by teamco** [react-component/picker#755]
detail: TypeError: generateConfig[fn] is not a function
          at /home/frontend/node_modules/antd/node_modules/rc-picker/lib/utils/dateUtil.js:157:35
          at Array.forEach (<anonymous>)
          at forEach (/home/frontend/node_modules/antd/node_modules/rc-picker/lib/utils/dateUtil.js:153:9)
          at /home/frontend/node_modules/antd/node_modules/rc-picker/lib/PickerInput/hooks/useRangePickerValue.js:84:59
          at nextCreate (/home/frontend/node_modules/react-dom/cjs/react-dom.development.js:15846:19)
          at Object.mountMemo [as useMemo] (/home/frontend/node_modules/react-dom/cjs/react-dom.development.js:16219:16)
          at Object.useMemo (/home/frontend/node_modules/react/cjs/react.development.js:1532:21)
          at useMemo (/home/frontend/node_modules/antd/node_modules/rc-picker/lib/PickerInput/hooks/useRangePickerValue.js:80:34)
          at Picker (/home/frontend/node_modules/antd/node_modules/rc-picker/lib/PickerInput/SinglePicker.js:200:63)

**Comment by teamco** [comment]
"antd": "^5.13.3",
...
"rc-picker" (in deps): "3.14.6"

**Comment by teamco** [comment]
It seems like the error with moment.js usage
Uncaught [TypeError: generateConfig[fn] is not a function]
- setMillisecond is not a function.
- getMillisecond is not a function.

**Comment by wasd0109** [comment]
Having the same issue, this seems to be caused by a mismatch of the rc-picker and antd dependency.
Antd uses a version of rc-picker which export a get/setMillisecond method but the specified rc-picker version does not have that method
